/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as govStandard from "./gov_standard";
export type { govStandard };
export type { Box } from "./Box";
export type { GovToken } from "./GovToken";
