/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as govStandard from "./gov_standard";
export { Box__factory } from "./Box__factory";
export { GovToken__factory } from "./GovToken__factory";
